export const SET_PASSWORD = 'SET_PASSWORD';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';

export const REQUEST_SESSION_HISTORY = 'REQUEST_SESSION_HISTORY';
export const RECEIVE_SESSION_HISTORY = 'RECEIVE_SESSION_HISTORY';
export const SELECT_PREV_SESSION = 'SELECT_PREV_SESSION';

export const REQUEST_CAMPUSES = 'REQUEST_CAMPUSES';
export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const SET_CAMPUSES = 'SET_CAMPUSES';

export const REQUEST_BUILDINGS = 'REQUEST_BUILDINGS';
export const RECEIVE_BUILDINGS = 'RECEIVE_BUILDINGS';
export const SET_BUILDINGS = 'SET_BUILDINGS';

export const REQUEST_ROOMS = 'REQUEST_ROOMS';
export const RECEIVE_ROOMS = 'RECEIVE_ROOMS';
export const SET_ROOMS = 'SET_ROOMS';

export const SELECT_CAMPUS = 'SELECT_CAMPUS';
export const DESELECT_CAMPUS = 'DESELECT_CAMPUS';
export const COMMIT_CAMPUS_SELECTION = 'COMMIT_CAMPUS_SELECTION';
export const SELECT_BUILDING = 'SELECT_BUILDING';
export const DESELECT_BUILDING = 'DESELECT_BUILDING';
export const COMMIT_BUILDING_SELECTION = 'COMMIT_BUILDING_SELECTION';
export const SELECT_ROOM = 'SELECT_ROOM';  
export const DESELECT_ROOM = 'DESELECT_ROOM';  
export const COMMIT_ROOM_SELECTION = 'COMMIT_ROOM_SELECTION';


export const SELECT_WORKSTATION = 'SELECT_WORKSTATION';
export const DESELECT_WORKSTATION = 'DESELECT_WORKSTATION';
export const SELECT_END_TIME = 'SELECT_END_TIME';
export const DESELECT_ALL_WORKSTATIONS = 'DESELECT_ALL_WORKSTATIONS';
export const SELECT_ALL_WORKSTATIONS = 'SELECT_ALL_WORKSTATIONS';

export const REQUEST_START_SESSION = 'REQUEST_START_SESSION';
export const RECEIVE_START_SESSION_RESPONSE = 'RECEIVE_START_SESSION_RESPONSE';
export const START_SESSION = 'START_SESSION';  
export const END_SESSION = 'END_SESSION';  

export const REQUEST_ENABLE_WORKSTATION = 'REQUEST_ENABLE_WORKSTATION';
export const RESPONSE_ENABLE_WORKSTATION = 'RESPONSE_ENABLE_WORKSTATION';

export const REQUEST_DISABLE_WORKSTATION = 'REQUEST_DISABLE_WORKSTATION';
export const RESPONSE_DISABLE_WORKSTATION = 'RESPONSE_DISABLE_WORKSTATION';

export const REQUEST_ENABLE_ALL_WORKSTATIONS = 'REQUEST_ENABLE_ALL_WORKSTATIONs';
export const RESPONSE_ENABLE_ALL_WORKSTATIONS = 'RESPONSE_ENABLE_ALL_WORKSTATIONS';  

export const REQUEST_DISABLE_ALL_WORKSTATIONS = 'REQUEST_DISABLE_ALL_WORKSTATIONS';  
export const RESPONSE_DISABLE_ALL_WORKSTATIONS = 'RESPONSE_DISABLE_ALL_WORKSTATIONS';

export const REQUEST_ADD_WORKSTATION_TO_WORKGROUP = 'REQUEST_ADD_WORKSTATION_TO_WORKGROUP';
export const RESPONSE_ADD_WORKSTATION_TO_WORKGROUP = 'RESPONSE_ADD_WORKSTATION_TO_WORKGROUP';

export const REQUEST_REMOVE_WORKSTATION_FROM_WORKGROUP = 'REQUEST_REMOVE_WORKSTATION_FROM_WORKGROUP';
export const RESPONSE_REMOVE_WORKSTATION_FROM_WORKGROUP = 'RESPONSE_REMOVE_WORKSTATION_FROM_WORKGROUP';

