export const REQUEST_CAMPUSES = 'REQUEST_CAMPUSES';
export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const SET_CAMPUSES = 'SET_CAMPUSES';

export const REQUEST_BUILDINGS = 'REQUEST_BUILDINGS';
export const RECEIVE_BUILDINGS = 'RECEIVE_BUILDINGS';
export const SET_BUILDINGS = 'SET_BUILDINGS';

export const REQUEST_ROOMS = 'REQUEST_ROOMS';
export const RECEIVE_ROOMS = 'RECEIVE_ROOMS';
export const SET_ROOMS = 'SET_ROOMS';

export const REQUEST_SESSION_HISTORY = 'REQUEST_SESSION_HISTORY';
export const RECEIVE_SESSION_HISTORY = 'RECEIVE_SESSION_HISTORY';

export const SELECT_PREV_SESSION = 'SELECT_PREV_SESSION';

export const SELECT_CAMPUS = 'SELECT_CAMPUS';
export const DESELECT_CAMPUS = 'DESELECT_CAMPUS';
export const COMMIT_CAMPUS_SELECTION = 'COMMIT_CAMPUS_SELECTION';
export const SELECT_BUILDING = 'SELECT_BUILDING';
export const DESELECT_BUILDING = 'DESELECT_BUILDING';
export const COMMIT_BUILDING_SELECTION = 'COMMIT_BUILDING_SELECTION';
export const SELECT_ROOM = 'SELECT_ROOM';  
export const DESELECT_ROOM = 'DESELECT_ROOM';  
export const COMMIT_ROOM_SELECTION = 'COMMIT_ROOM_SELECTION';
export const ADD_WORKSTATION = 'ADD_WORKSTATION';  
export const REMOVE_WORKSTATION = 'REMOVE_WORKSTATION';  
export const DISABLE_WORKSTATION = 'DISABLE_WORKSTATION';  
export const DISABLE_WORKSTATIONS = 'DISABLE_WORKSTATIONS';  

export const SELECT_WORKSTATION = 'SELECT_WORKSTATION';
export const DESELECT_WORKSTATION = 'DESELECT_WORKSTATION';
export const SELECT_END_TIME = 'SELECT_END_TIME';
export const DESELECT_ALL_WORKSTATIONS = 'DESELECT_ALL_WORKSTATIONS';
export const SELECT_ALL_WORKSTATIONS = 'SELECT_ALL_WORKSTATIONS';

export const REQUEST_START_SESSION = 'REQUEST_START_SESSION';
export const RECEIVE_START_SESSION_RESPONSE = 'RECEIVE_START_SESSION_RESPONSE';
export const START_SESSION = 'START_SESSION';  
export const END_SESSION = 'END_SESSION';  

export const ADD_WORKSTATION_TO_WORKGROUP = 'ADD_WORKSTATION_TO_WORKGROUP';
export const REMOVE_WORKSTATION_FROM_WORKGROUP = 'REMOVE_WORKSTATION_FROM_WORKGROUP';