export const REQUEST_BUILDINGS = 'REQUEST_BUILDINGS';
export const RECEIVE_BUILDINGS = 'RECEIVE_BUILDINGS';
export const SET_BUILDINGS = 'SET_BUILDINGS';

export const REQUEST_SESSION_HISTORY = 'REQUEST_SESSION_HISTORY';
export const RECEIVE_SESSION_HISTORY = 'RECEIVE_SESSION_HISTORY';

export const SELECT_PREV_SESSION = 'SELECT_PREV_SESSION';

export const SELECT_BUILDING = 'SELECT_BUILDING';
export const DESELECT_BUILDING = 'DESELECT_BUILDING';
export const COMMIT_BUILDING_SELECTION = 'COMMIT_BUILDING_SELECTION';
export const SELECT_ROOM = 'SELECT_ROOM';  
export const DESELECT_ROOM = 'DESELECT_ROOM';  
export const COMMIT_ROOM_SELECTION = 'COMMIT_ROOM_SELECTION';
export const START_SESSION = 'START_SESSION';  
export const END_SESSION = 'END_SESSION';  
export const ADD_WORKSTATION = 'ADD_WORKSTATION';  
export const REMOVE_WORKSTATION = 'REMOVE_WORKSTATION';  
export const DISABLE_WORKSTATION = 'DISABLE_WORKSTATION';  
export const DISABLE_WORKSTATIONS = 'DISABLE_WORKSTATIONS';  
